### ISSUE TITLE
PreTeXtual not showing up in "Install Packages"

### ISSUE THREAD

**Issue by aluminum1** [daverosoff/MBXTools#42] opened 2019-04-23 08:50 UTC
PreTeXtual doesn't show up under "Install Packages" on my (recent) version of Sublime Text, version 3.2.1.

Kind regards
Bruce Bartlett

**Comment by daverosoff** [comment] 2019-04-28 20:22
Thanks for the message. I will look into it. What OS are you running, and which Sublime build number?

**Comment by daverosoff** [comment] 2019-05-30 19:31
I'm still unable to reproduce this error. Closing the issue for now.

**Closed as completed by daverosoff** 2019-05-30 19:31 UTC
